/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package BytecodeTokenizer;

public class Main {
    /*
    input: 1) option, 2) file list path, 3) output path
    (example) link ../BytecodeReader/deeplearning4j_file_list.txt ./
    (example) raw ../BytecodeReader/deeplearning4j_file_list.txt ./
    output: tokenized files
     */

    public static void main(String[] args){
        long start = System.currentTimeMillis();
        if(args.length != 3){
            System.err.println("input: 1) option, 2) file list path, 3) output path with project name and option\n" +
                    "    (example) link ../BytecodeReader/deeplearning4j_file_list.txt ./RxJava_link\n" +
                    "    (example) raw ../BytecodeReader/deeplearning4j_file_list.txt ./RxJava\n");
            System.exit(-1);
        }
        String option = args[0];
        if(!option.equals("link") && !option.equals("raw")){
            System.err.println("input: 1) option, 2) file list path, 3) output path\n" +
                    "    (example) link ../BytecodeReader/deeplearning4j_file_list.txt ./\n" +
                    "    (example) raw ../BytecodeReader/deeplearning4j_file_list.txt ./\n");
            System.exit(-1);
        }
        String fileListPath = args[1];
        String outputPath = args[2];
        BytecodeTokenizer t = new BytecodeTokenizer(fileListPath);
        if(option.equals("link")){
            t.linkTokenize(outputPath);
        } else {
            t.tokenize(outputPath);
        }
        System.out.println("Running Time (sec): " + ((System.currentTimeMillis() - start) / 1000));
    }
}
